version: "3.8"
services:
    pokedex:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        ports:
            - 8080:8080
        environment:
            - PORT=8080