version: '3.7'

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
    env_file:
      - .env
    restart: always
  api:
    build: src/
    volumes:
      - ./src/:/usr/src/app/
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db
    environment:
      - PORT=8000
    ports:
      - "80:8000"
